### ISSUE TITLE
Documentation for `probe-search` module

### ISSUE THREAD

**Issue by jstol** [ctongfei/feature#1]
Hi Tongfei, are there are any plans to add a README for the `probe-search` module?

**Comment by ctongfei** [comment]
Sorry for your inconvenience. It'll be ready soon.

-- Tongfei (from mobile)

**Comment by ctongfei** [comment]
I've just outlined the basic usage. Will elaborate later (very busy, sorry)

**Comment by jstol** [comment]
Great, thanks!
